### ISSUE TITLE
Replace front-door with traffic manager

### ISSUE THREAD

**Issue by DavidDury** [Azure/Mission-Critical-Online#959] opened 2023-05-11 09:33 UTC
I would like to replace Azure Front Door with Azure Traffic Manager because of need to support Layer 4 TCP Connectivity. Any advise on this scenario ? I can see that the magic happens in frontdoor.tf. Most likely this will have to be changed as traffic is handled differently in Traffic Manager and there is no need for CDN.

Any advise in the right direction will be appreciated.

**Comment by sebader** [comment] 2023-06-05 10:52
Duplicate of https://github.com/Azure/Mission-Critical-Connected/issues/551

**Closed by sebader** 2023-06-05 10:52 UTC
